[package]
name = "everything-next"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[lints]
workspace = true

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
everything-core = { path = "../crates/everything-core" }
everything-engine = { path = "../crates/everything-engine" }
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2.4.3"
tauri-plugin-window-state = "2.4.1"
tokio = { version = "1", features = ["sync"] }
windows-shell = { path = "../crates/windows-shell" }
