[package]
name = "windows-shell"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
base64 = "0.22"
everything-core = { path = "../everything-core" }
image = { version = "0.25", default-features = false, features = ["png"] }
open = "5"
parking_lot = "0.12"
thiserror = "2"
trash = "5"

[target.'cfg(windows)'.dependencies]
clipboard-win = "5.4.1"
file_icon_provider = "1.0.0"
